apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ckan.fullname" . }}-ckan
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ template "ckan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ckan.name" . }}-ckan
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ckan.name" . }}-ckan
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: init-postgres
          image: busybox:1.32.1
          command: ['sh', '-c', "until nslookup ckan-postgres.ckan.svc.cluster.local; do echo waiting for postgres; sleep 5; done"]
        - name: init-solr
          image: busybox:1.32.1
          command: ['sh', '-c', "until nslookup ckan-solr.ckan.svc.cluster.local; do echo waiting for solr; sleep 5; done"]
        - name: init-redis
          image: busybox:1.32.1
          command: ['sh', '-c', "until nslookup ckan-redis.ckan.svc.cluster.local; do echo waiting for redis; sleep 5; done"]
        - name: init-ckan
          image: "{{ .Values.image.ckan.repository }}:{{ .Values.image.ckan.tag }}"
          imagePullPolicy: {{ .Values.image.ckan.pullPolicy }}
          command: {{ .Values.image.ckan.initCommand | toJson }}
          env:
          - name: CKAN_INI
            value: /etc/ckan/ckan.ini
          volumeMounts:
          - name: ckan-config
            mountPath: /etc/ckan/ckan.ini
            subPath: ckan.ini
          - name: who-ini-config
            mountPath: /etc/ckan/who.ini 
            subPath: who.ini
          - name: uwsgi-ini-config
            mountPath: /etc/ckan/uwsgi.ini 
            subPath: uwsgi.ini
          - name: wsgi-py-config
            mountPath: /etc/ckan/wsgi.py 
            subPath: wsgi.py
      volumes:
        - name: ckan-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: ckan.ini
              path: ckan.ini
        - name: who-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: who.ini
              path: who.ini
        - name: uwsgi-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: uwsgi.ini
              path: uwsgi.ini
        - name: wsgi-py-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: wsgi.py
              path: wsgi.py

      containers:
        - name: ckan
          image: "{{ .Values.image.ckan.repository }}:{{ .Values.image.ckan.tag }}"
          imagePullPolicy: {{ .Values.image.ckan.pullPolicy }}
          command: {{ .Values.image.ckan.command | toJson }}
          ports:
            - containerPort: {{ .Values.image.ckan.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.image.ckan.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: CKAN_INI
            value: /etc/ckan/ckan.ini
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: ckan-config
            mountPath: /etc/ckan/ckan.ini
            subPath: ckan.ini
          - name: who-ini-config
            mountPath: /etc/ckan/who.ini 
            subPath: who.ini
          - name: uwsgi-ini-config
            mountPath: /etc/ckan/uwsgi.ini 
            subPath: uwsgi.ini
          - name: wsgi-py-config
            mountPath: /etc/ckan/wsgi.py 
            subPath: wsgi.py
{{ if .Values.persistentVolume.nfs.enabled }}
          - name: ckan-data
            mountPath: /data/ckan
{{ end }}
      volumes:
        - name: ckan-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: ckan.ini
              path: ckan.ini
        - name: who-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: who.ini
              path: who.ini
        - name: uwsgi-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: uwsgi.ini
              path: uwsgi.ini
        - name: wsgi-py-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: wsgi.py
              path: wsgi.py

{{ if .Values.persistentVolume.nfs.enabled }}
        - name: ckan-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
{{ end }}
