apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ckan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ template "ckan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ckan.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ckan.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ckan
          image: "{{ .Values.image.ckan.repository }}:{{ .Values.image.ckan.tag }}"
          imagePullPolicy: {{ .Values.image.ckan.pullPolicy }}
          command: {{ .Values.image.ckan.command | toJson }}
          ports:
            - containerPort: {{ .Values.image.ckan.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.image.ckan.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: CKAN_SOLR_URL
            value: {{ .Values.environment.ckan.CKAN_SOLR_URL }}:{{ .Values.image.solr.port }}/{{ .Values.image.solr.ckanUrlPath }}
          - name: CKAN_REDIS_URL
            value: {{ .Values.environment.ckan.CKAN_REDIS_URL }}:{{ .Values.image.redis.port }}
          - name: CKAN_SITE_URL
            value: {{ .Values.environment.ckan.CKAN_SITE_URL }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: ckan-config
            mountPath: {{ .Values.volumes.mountPath }}/ckan.ini
            subPath: ckan.ini
          # - name: ckan-apache-config
          #   mountPath: /etc/apache2/sites-available
{{ if .Values.persistentVolume.nfs.enabled }}
          - name: ckan-data
            mountPath: /data/ckan
{{ end }}
      volumes:
        - name: ckan-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: ckan.ini
              path: ckan.ini
        - name: who-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: who.ini
              path: who.ini
{{ if .Values.persistentVolume.nfs.enabled }}
        - name: ckan-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
{{ end }}
