{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "ckan.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ckan.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: {{ .Values.ingress.ckan.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "ckan.fullname" . }}
              servicePort: {{ .Values.image.ckan.port }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
