---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ckan.fullname" . }}-rq-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}-rq-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "ckan.name" . }}-rq-worker
      release: {{ .Release.Name }}
  replicas: {{ .Values.image.rqWorker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "ckan.name" . }}-rq-worker
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
        - name: ckan-rq-worker
          image: "{{ .Values.image.ckan.repository }}:{{ .Values.image.ckan.tag }}"
          imagePullPolicy: {{ .Values.image.ckan.pullPolicy }}
          command: {{ .Values.image.rqWorker.command | toJson }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: ckan-config
            mountPath: /etc/ckan/ckan.ini
            subPath: ckan.ini
          - name: who-ini-config
            mountPath: /etc/ckan/who.ini
            subPath: who.ini
      volumes:
        - name: ckan-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: ckan.ini
              path: ckan.ini            
        - name: who-ini-config
          configMap:
            name: {{ template "ckan.fullname" . }}-config-map
            items:
            - key: who.ini
              path: who.ini
