---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ckan.fullname" . }}-ckan
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ckan
      protocol: TCP
      port: {{ .Values.image.ckan.port }}
      targetPort: {{ .Values.image.ckan.port }}
  selector:
    app: {{ template "ckan.name" . }}-ckan
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ckan.fullname" . }}-solr
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: solr
      protocol: TCP
      port: {{ .Values.image.solr.port }}
      targetPort: {{ .Values.image.solr.port }}
  selector:
    app: {{ template "ckan.name" . }}-solr
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ckan.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.image.redis.port }}
      targetPort: {{ .Values.image.redis.port }}
  selector:
    app: {{ template "ckan.name" . }}-redis
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ckan.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ckan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.image.postgres.port }}
      targetPort: {{ .Values.image.postgres.port }}
  selector:
    app: {{ template "ckan.name" . }}-postgres
    release: {{ .Release.Name }}
